pipeline {
    agent any
    tools {
        nodejs 'NodeJs-12'
    }
    stages {
        stage ('Clone Git'){
            steps {
                git branch: 'main', credentialsId: '6544f0f8-a427-4d3a-b61b-04fdc1edbfe0', url: 'https://github.com/khergner/DevOps-Training.git'
            }
        }
        stage('Install Dependencies'){
            steps {
                dir ('nodejs'){
                 sh '''
                 ls -la
                 npm install
                 '''
                }
            }
        }
    }
}