version: '3.8'
services: 
  jira:
    image: 
    container_name: jira-core
    environment: 
      - JVM_MINIMUM_MEMORY=1g
      - JVM_MAXIMUM_MEMORY=6g
      - JVM_RESERVED_CODE_CACHE_SIZE=1g
    ports: 
      - "8080:8080"
    volumes: 
      - jiraVolume:/var/atlassian/application-data/jira
    network_mode: bridge
    restart: always
volumes: 
  jiraVolume: